/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetojoguinho;

/**
 *
 * @author Pichau
 */
public class Joguinho extends javax.swing.JFrame {
        
        setSize(100,100);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(this);
        setVisible(true);
    }
public boolean joga= true;
public boolean jogb= true;
public int contapos = 0;
public int k = 0, i = 0;
int op;
public String linha1, linha2, linha3, coluna1, coluna2, coluna3, diagonal1, diagonal2;
String[][]posvetor = new String[3][3];
    /**
     * Creates new form Joguinho
     */
    public Joguinho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_restart = new javax.swing.JButton();
        tela_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_1.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_4.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_7.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_restart.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_restart.setText("Recomeçar");
        btn_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restartActionPerformed(evt);
            }
        });

        tela_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tela_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tela_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tela_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btn_restart, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tela_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_restart, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void verificaJogadorAouB(){
        if(joga==true && jogb==true) {
            this.op = 1;
            joga = false;
            jogb = true;
            tela_txt.setText("Jogue, player O");
        }
        else if(joga==true && jogb ==false) {
            this.op = 1;
            joga = false;
            jogb = true;
            tela_txt.setText("Jogue, player O");
        }
        else {
            this.op = 2;
            joga = true;
            jogb = false;
            tela_txt.setText("Jogue, player X");
        }
    }
    public void limparPosicoes(){
    for(i=0; i<3; i++){
       for(k=0; k<3; k++){
           posvetor[i][k]="";
           System.out.println(posvetor[i][k]);
       }     
      }
    }
    public void desativaBotoes(){
        btn_1.setEnabled(false);
        btn_2.setEnabled(false);
        btn_3.setEnabled(false);
        btn_4.setEnabled(false);
        btn_5.setEnabled(false);
        btn_6.setEnabled(false);
        btn_7.setEnabled(false);
        btn_8.setEnabled(false);
        btn_9.setEnabled(false);
        
    }
    public void verificarPos(){
        contapos=0;
       for(i=0; i<3; i++){
       for(k=0; k<3; k++){
           if(posvetor[i][k]== "x"|posvetor[i][k]=="o"){
                contapos+=1;
           } 
    }
    }
    }
    public void verificarVencedor(){
        linha1 = posvetor[0][0] + posvetor [0][1] + posvetor [0] [2];
        linha2 = posvetor[1][0] + posvetor [1][1] + posvetor [1] [2];
        linha3 = posvetor[2][0] + posvetor [2][1] + posvetor [2] [2];
        
        coluna1 = posvetor [0][0] + posvetor [1] [0] + posvetor [2] [0];
        coluna2 = posvetor [0][1] + posvetor [1] [1] + posvetor [2] [1];
        coluna3 = posvetor [0][2] + posvetor [1] [2] + posvetor [2] [2];
        
        diagonal1 = posvetor[0][0] + posvetor [1][1] + posvetor[2][2];
        diagonal2 = posvetor[0][2] + posvetor [1][1] + posvetor[2][0];
        
        if(linha1.equals("xxx")|linha2.equals("xxx")|linha3.equals("xxx")|coluna1.equals("xxx")|coluna2.equals("xxx")|coluna3.equals("xxx")|diagonal1.equals("xxx")|diagonal2.equals("xxx")){
            tela_txt.setText("Parabéns X, você venceu!");
            desativaBotoes();
        }
        else if(linha1.equals("ooo")|linha2.equals("ooo")|linha3.equals("ooo")
           |coluna1.equals("ooo")|coluna2.equals("ooo")|coluna3.equals("ooo")
           |diagonal1.equals("ooo")|diagonal2.equals("ooo")){
            tela_txt.setText("Parabéns O, você venceu!");
            desativaBotoes();
        }
        else if(contapos==9){
            tela_txt.setText("Empate");
        }
            
    }
    
    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        verificaJogadorAouB();
        if(op==1){    
        btn_1.setText("X");
        posvetor[0][0] = "x";
        }
        else {
        btn_1.setText("O");
        posvetor[0][0] = "o";
        }
        btn_1.setEnabled(false);
        verificarPos();
        verificarVencedor();
      
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
         verificaJogadorAouB();
        if(op==1){    
        btn_2.setText("X");
        posvetor[0][1] = "x";
        }
        else {
        btn_2.setText("O");
        posvetor[0][1] = "o";
        }
        btn_2.setEnabled(false);
        verificarPos();
        verificarVencedor();
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
         verificaJogadorAouB();
        if(op==1){    
        btn_3.setText("X");
        posvetor[0][2] = "x";
        }
        else {
        btn_3.setText("O");
        posvetor[0][2] = "o";
        }
        btn_3.setEnabled(false);
        verificarPos();
        verificarVencedor();
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
         verificaJogadorAouB();
        if(op==1){    
        btn_4.setText("X");
        posvetor[1][0] = "x";
        }
        else {
        btn_4.setText("O");
        posvetor[1][0] = "o";
        }
        btn_4.setEnabled(false);
        verificarPos();
        verificarVencedor();
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
           verificaJogadorAouB();
        if(op==1){    
        btn_5.setText("X");
        posvetor[1][1] = "x";
        }
        else {
        btn_5.setText("O");
        posvetor[1][1] = "o";
        }
        btn_5.setEnabled(false);
        verificarPos();
        verificarVencedor();
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
           verificaJogadorAouB();
        if(op==1){    
        btn_6.setText("X");
        posvetor[1][2] = "x";
        }
        else {
        btn_6.setText("O");
        posvetor[1][2] = "o";
        }
        btn_6.setEnabled(false);
        verificarPos();
        verificarVencedor();
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
           verificaJogadorAouB();
        if(op==1){    
        btn_7.setText("X");
        posvetor[2][0] = "x";
        }
        else {
        btn_7.setText("O");
        posvetor[2][0] = "o";
        }
        btn_7.setEnabled(false);
        verificarPos();
        verificarVencedor();
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
           verificaJogadorAouB();
        if(op==1){    
        btn_8.setText("X");
        posvetor[2][1] = "x";
        }
        else {
        btn_8.setText("O");
        posvetor[2][1] = "o";
        }
        btn_8.setEnabled(false);
        verificarPos();
        verificarVencedor(); 
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
           verificaJogadorAouB();
        if(op==1){    
        btn_9.setText("X");
        posvetor[2][2] = "x";
        }
        else {
        btn_9.setText("O");
        posvetor[2][2] = "o";
        }
        btn_9.setEnabled(false);
        verificarPos();
        verificarVencedor(); 
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restartActionPerformed
        //Reinicia o jogo
        btn_1.setText("");
        btn_1.setEnabled(true);
        
        btn_2.setText("");
        btn_2.setEnabled(true);
        
        btn_3.setText("");
        btn_3.setEnabled(true);
        
        btn_4.setText("");
        btn_4.setEnabled(true);
        
        btn_5.setText("");
        btn_5.setEnabled(true);
        
        btn_6.setText("");
        btn_6.setEnabled(true);
     
        btn_7.setText("");
        btn_7.setEnabled(true);
        
        btn_8.setText("");
        btn_8.setEnabled(true);
        
        btn_9.setText("");
        btn_9.setEnabled(true);
        limparPosicoes();
        tela_txt.setText("");
        joga = true;
        jogb = true;
    }//GEN-LAST:event_btn_restartActionPerformed

    private void tela_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tela_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tela_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Joguinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Joguinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Joguinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Joguinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Joguinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_restart;
    private javax.swing.JTextField tela_txt;
    // End of variables declaration//GEN-END:variables
}
